### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by Woren** [googlesamples/apk-patch-size-estimator#2]
Hello,
I got exception after few seconds of running python script on Windows 10 using Cygwin (bsdiff and python installed). Maybe there is some hardcoded path which is not working on Windows / Cygwin? Cygwin is run under "Adminstrator" privileges.

python apk_patch_size_estimator.py --old-file old.apk --new-file new.apk

```
Exception in thread "main" java.io.FileNotFoundException: \tmp\patch.tmp.filebyfile (System can't find path)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.archivepatcher.tools.FileByFileTool.generatePatch(FileByFileTool.java:199)
        at com.google.archivepatcher.tools.FileByFileTool.run(FileByFileTool.java:156)
        at com.google.archivepatcher.tools.FileByFileTool.main(FileByFileTool.java:100)
Traceback (most recent call last):
  File "apk_patch_size_estimator.py", line 350, in <module>
    main()
  File "apk_patch_size_estimator.py", line 325, in main
    args.old_file, args.new_file, save_patch_path, temp_path)
  File "apk_patch_size_estimator.py", line 267, in calculate_filebyfile
    'Problem creating file by file patch, returned code: %s' % ret_code)
Exception: Problem creating file by file patch, returned code: 1
```

**Comment by juliantoledo** [comment]
Thank you @Woren for reporting this issue, I will check it out soon.

**Comment by jeffason** [comment]
I recommend using WSL on Windows rather than cygwin/msys.  I had issues in the latter environments as well but everything is running great in a WSL Ubuntu installation
